name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hugo-deploy-gh-pages
      uses: linuxsuren/surenpi@master
      env:
        GIT_DEPLOY_KEY: ${{ secrets.HUGO }}
        HUGO_VERSION: "0.68.3"
        WEBSITE_GIT: "git@github.com:testytestytesttest/testytestytesttest.github.io.git"
        WEBSITE_DIR: "testytestytesttest.github.io"
